### PR TITLE
Dark Theme qss cleanup

### PR DESCRIPTION
**Pull request by adasauce**
cleanup
re-order
de-duplicate
re-dry

should help maintaining down the road, keep display bugs wrangled, and give people adding new features a good base to add onto instead of copy/pasting more stuff and guessing.

### CODE REVIEW

**Comment by adasauce** [comment]
^^ not sure why it's complaining about a merge conflict. mine obviously removes those lines and puts them above.

pretty sure i wouldn't have that code to move if it wasn't in my git history.

**Comment by deepbluev7** [comment]
Maybe try rebasing this on top of the current 0.7.0 branch? Do you intend to also clean up the other qss files similarly? Otherwise 60 lines deleted! Awesome!

**Comment by adasauce** [comment]
ah yea, my mirror hadn't synced those changes into its 0.7.0 when i started the branch.

we synced and rebased now.

I should be able to do the others pretty quickly too. maybe I can just include those in this PR then, and we'll merge it all in.

**Comment by deepbluev7** [comment]
Sounds good

**Comment by adasauce** [comment]
there, I think that's a pretty good cleanup and dedup.

the system theme cleanup broke my eyes

**Comment by deepbluev7** [comment]
Yep, that looks pretty good and I couldn't find any breakage. Thank you! I would have never found the motivation to do that... >.<

**Pull request merged**
