### PR TITLE
Add qtkeychain to install lists

### PR DESCRIPTION
**Pull request by LorenDB**

### CODE REVIEW

**Comment by deepbluev7** [comment]
I think it may also be a good idea to list QtKeychain in the build deps? Thank you very much for cleaning up after my lazy bum! <3

**Comment by LorenDB** [comment]
Any specific version of qtkeychain required?

**Comment by deepbluev7** [comment]
I don't think so, only requirements are that the platform you are using is supported by that qtkeychain version as well as qt5 support. I wouldn't mention any version.

**Comment by deepbluev7** [comment]
:tada:

**Pull request merged**
