### PR TITLE
Show an indicator in the timeline for mods and admins

### PR DESCRIPTION
**Pull request by LorenDB**
The other day somebody suggested in #nheko:nheko.im that usernames should be colored differently if the user is a mod or admin. I decided to try implementing this instead.

I have no idea if this actually a feature we want to merge, but I'll throw it out there anyway :)

### CODE REVIEW

**Comment by deepbluev7** [comment]
Hm, that is not a bad solution, but let me think about it for 2 days and ping me again then :D

**Comment by LorenDB** [comment]
@deepbluev7 ping

**Comment by deepbluev7** [comment]
Sorry, but I don't know what that command means.

Thanks for asking 🥰

**Comment by deepbluev7** [comment]
The location is a bit weird, isn't it?

image

Between or before probably looks more natural?

**Comment by deepbluev7** [comment]
There. Slightly better but maybe we'll improve it a bit later :D

**Pull request merged**
