### PR TITLE
fixed a typo in a comment

### PR DESCRIPTION
**Pull request by AyuBisht**
Changed it to "level" from "leve"

### CODE REVIEW

**Comment by deepbluev7** [comment]
Thank you :3

**Comment by deepbluev7** [comment]
Thank you :3

**Comment by AyuBisht** [comment]
No problem!
Hey @deepbluev7 Is it okay to directly make such pull requests?

**Comment by deepbluev7** [comment]
Sure. Please also make a PR to the master branch. Your PR was to the wrong branch, so it didn't actually get merged into master. If you make a single commit that fixes both typos, that will probably be the easiest way to fix that.

**Comment by AyuBisht** [comment]
okay, noted!
Thank you @deepbluev7

**Pull request merged**
