### PR TITLE
Added ability to build with packaged version of cpp-httplib

### PR DESCRIPTION
**Pull request by xvitaly**
Added ability to build with packaged version of cpp-httplib.

### CODE REVIEW

**Comment by LorenDB** [comment]
Thanks for the PR! This does make me think, though: it appears that we are only using cpp-httplib in the SSO handler at this point. We should maybe look into porting that to coeurl to eliminate this dependency.

**Review by LorenDB — APPROVED** [review]
LGTM without having actually tried it. This will probably wreak havoc with some of our CI runners though if we forget to add -DUSE_BUNDLED_CPPHTTPLIB though :P

**Comment by deepbluev7** [comment]
> Thanks for the PR! This does make me think, though: it appears that we are only using cpp-httplib in the SSO handler at this point. We should maybe look into porting that to coeurl to eliminate this dependency.

Won't work, coeurl is a client, httplib is a server. We can someday switch to the Qt one though.

**Comment by deepbluev7** [comment]
Thank you!

**Comment by LorenDB** [comment]
> Won't work, coeurl is a client, httplib is a server. We can someday switch to the Qt one though.
Oh, duh, I should have looked closer. Yeah, the Qt 6 one probably would do the trick.

**Pull request merged**
