### PR TITLE
Update README with reference to Debian package

### PR DESCRIPTION
**Pull request by protesilaos**
I just discovered the [nheko Debian package](https://packages.debian.org/buster/nheko). It is available in the current stable release (Debian 10 'buster') or higher.

### CODE REVIEW

**Comment by deepbluev7** [comment]
Hm  that package still references the old version, i.e. not Nheko-Reborn/nheko, but mujx/nheko, as far as I can tell. Thank you for your contribution and we'll definitely merge it, but we probably should contact the packager and tell him about 0.6.4 and the new repo.

**Comment by deepbluev7** [comment]
(as always the merge button doesn't work on my phone, will merge it once I get home...)

**Comment by deepbluev7** [comment]
Scratch that, the unstable variants also package the correct release, so everything is fine :D

**Comment by protesilaos** [comment]
Thank you for your efforts!

**Pull request merged**
