### PR TITLE
Add call invite screen for mobile

### PR DESCRIPTION
**Pull request by trilene**

### CODE REVIEW

**Comment by deepbluev7** [comment]
Okay looks good, but I think there is still a small issue with the call accept and deny buttons:

image

**Comment by trilene** [comment]
Thanks Nico. I only tested on i3 and GNOME. Should've tried on KDE as well. I replicate your issue there - will take a look.

**Comment by trilene** [comment]
This should look a bit better now.

**Comment by deepbluev7** [comment]
Yep, seems to work now! :D

**Pull request merged**
