### PR TITLE
Add repology badge to readme

### PR DESCRIPTION
**Pull request by not-chicken**

### CODE REVIEW

**Comment by deepbluev7** [comment]
Thanks, that is very helpful! :D

**Comment by deepbluev7** [comment]
Ah, I merged it a bit fast. Do you think it would look better, if we would put it in the first row with all the other badges? It would be harder to find there though...

**Comment by not-chicken** [comment]
I initially put it there too, but as you said it kinda gets lost with other badges. I prefer the current location.

It's your call. : )

**Comment by deepbluev7** [comment]
It's fine, I'd say. if you already tried it, I trust your judgement :3

**Pull request merged**
