### PR TITLE
flick left to reply

### PR DESCRIPTION
**Pull request by maltee1**
Seems to work just fine.
The reply pops up once the flick has ended. Making it pop up when the threshold is reached awkward
It requires to keep the AdaptiveLayout within its bounds (otherwise the two flicks will overlay in a really non-intuitive way)
flick right to go back to the rooms list still works the same. Right flick of timelinerow is minimal. Any chance of this causing problems?

### CODE REVIEW

**Comment by maltee1** [comment]
I'm happy with how this works on my phone. The changing timelinewidth from the scrollbar magic and the ungrabbable areas make it a bit tricky to use at times. Once fixes for those are in master I can see whether any parameters need to be optimized.

**Comment by deepbluev7** [comment]
I somehow can't trigger a reply with this... it just does nothing :D

Also this is really frickly, when you are not already at the bottom of the timeline... Maybe a dragHandler is better suited for this?

**Comment by deepbluev7** [comment]
Oh, no, it actually works when I drag in the right direction... Can you lock the dragging in the other direction?

**Comment by maltee1** [comment]
In single page mode, flicking right just goes back to the rooms list, but I guess I forgot about multi-page mode. Flickable doesn't allow locking the direction, only the axis. I'll probably delete this branch and re-implement using a DragHandler.

**Comment by deepbluev7** [comment]
Well, maybe the drag handler doesn't work at all, but you can give it a try at least. You can also just implement it and force push over this branch :3

**Pull request closed without merging**
