### PR TITLE
updated readme.md features paragraph

### PR DESCRIPTION
**Pull request by Palash2911**
Made few changes in the features section under the readme file

### CODE REVIEW

**Comment by deepbluev7** [comment]
I don't really see how this change is an improvement, but maybe I am missing something as a not native speaker? @redsky17 ?

**Comment by Palash2911** [comment]
I made a grammatical change as it was my first contribution. Please forgive
my pull request if it has no contribution at all.

**Comment by deepbluev7** [comment]
This does just seem to change things without improving so much, so I am reluctant to accept it. While fixes to the README are appreciated, they should aim to make an actual improvement instead of just change to have contributed something. As such I will close this. I'm looking forward to any future contribution you will make and if you have any question, if a contribution would make sense, just ask in #nheko:nheko.im ;-)

**Comment by Palash2911** [comment]
Ok. Looking forward for contributing some actual code. Thanking you for
your support.

**Pull request closed without merging**
