### PR TITLE
QML all the things, part 3: Raw message dialog

### PR DESCRIPTION
**Pull request by LorenDB**

### CODE REVIEW

**Comment by deepbluev7** [comment]
Colors are wrong:

grafik

**Comment by LorenDB** [comment]
Phooey! Why do I always forget that?

**Comment by deepbluev7** [comment]
Because you don't test the dark mode?

**Comment by LorenDB** [comment]
Fixed

**Comment by deepbluev7** [comment]
Is this still a draft? Or do you think it is ready?

**Comment by LorenDB** [comment]
Oops! No, it's ready

**Comment by deepbluev7** [comment]
Still doesn't look right

**Comment by LorenDB** [comment]
It looks fine on my system

**Comment by deepbluev7** [comment]
Did you try the dark mode?

**Comment by deepbluev7** [comment]
The unrounded rectangle looks ugly, but I don't think there is a way around that right now. Thanks! :D

**Pull request merged**
