### PR TITLE
Moves the timestamp to the left

### PR DESCRIPTION
**Pull request by deepbluev7**
This should help a lot on mobile, makes the timeline a bit denser and
gives additional horizontal space. Not sure I like the smaller avatars
though.

grafik

### CODE REVIEW

**Comment by Bubu** [comment]
I guess I'd have to see that live in action to really judge. From a first glance it looks slightly more confusing as the avatars move somewhat in-between messages so it looks like it would be ahrder to tell at a glance to which message they belong.

**Comment by deepbluev7** [comment]
I think it actually makes it a bit easier in the case of replies, because it is attached to the actual message you wrote now. But I still sometimes mistake the timestamp as belonging into the message .-.

**Comment by Kirillpt** [comment]
Maybe better to place timestamp (and box) after nickname?
image

**Comment by vachan-maker** [comment]
This is how schildichat does it 
image

**Comment by deepbluev7** [comment]
I guess I need to redo this anyway... Stupid Github!

**Pull request closed without merging**
