### PR TITLE
Fix image copying on windows

### PR DESCRIPTION
**Pull request by NepNep21**

### CODE REVIEW

**Comment by NepNep21** [comment]
Drafted until the user that found the bug tests it fyi

**Comment by deepbluev7** [comment]
@labhub retry

**Comment by deepbluev7** [comment]
@labhub new-pipeline

**Comment by deepbluev7** [comment]
I think this makes enough sense to merge as is, do you want to undraft it?

**Comment by NepNep21** [comment]
> I think this makes enough sense to merge as is, do you want to undraft it?

I'd still like them to test it too just in case this wasn't the only issue (though it was in my case) and something else could also make it not work in their case, but your choice.

**Comment by deepbluev7** [comment]
I think it makes sense to merge it as is. That way it will be a signed build, that they can just update to to test and the fix looks sane to me.

**Comment by NepNep21** [comment]
Fair enough

**Comment by deepbluev7** [comment]
@labhub retry

**Comment by deepbluev7** [comment]
Sent **retry** command for pipeline [**5707**](https://nheko.im/nheko-reborn/nheko/pipelines/5707) on [**GitLab**](https://nheko.im/nheko-reborn/nheko)

Have a great day! 😄

**Pull request merged**
