### PR TITLE
Add settings option to display avatars as squares

### PR DESCRIPTION
**Pull request by pupper68k**
Addresses bug #71

### CODE REVIEW

**Comment by pupper68k** [comment]
Looks like I accidentally pulled it out in ce97858.
I put it back and tested the build.

**Comment by redsky17** [comment]
Could you run 'make lint' from the root directory so that the code is formatted according to our style rules?

**Comment by deepbluev7** [comment]
It works pretty well on my end, but maybe group the settings with the settings for the sidebar? Both are settings about UI Elements and having different groups for every single setting looks a bit weird imo?

**Comment by pupper68k** [comment]
Thanks for the feedback! I have grouped the toggle with the Group Sidebar toggle and applied the linter.

**Comment by deepbluev7** [comment]
Hm, looks like the linter is still complaining. It can a bit fickle at times. You could try running it manually via `clang-format -i path/to/file/it/is/complaining/about`? I had that issue myself, that make lint doesn't pick up my changes, but the CI does. Should probably figure out why it does that...

**Comment by deepbluev7** [comment]
Looks good now, thank you very much for your contribution!

**Pull request merged**
