### PR TITLE
Restore compatibility with clang-format v11

### PR DESCRIPTION
**Pull request by foresto**
The most recent .clang-format change (e6b6a76) added about 150 settings, a few of which aren't supported by clang-format v11. It broke the linter process for some linux distros, including Debian. This patch makes it work again by reverting the incompatible entries (and keeping the rest).

### CODE REVIEW

**Comment by deepbluev7** [comment]
I think we can actually revert https://github.com/Nheko-Reborn/nheko/commit/e6b6a76437920cb3abd72db2b28dd7570ee3b8ad completely. It didn't achieve the goal we wanted to achieve (which is format the same with clang-format 13 and 14). And that many options isn't really helpful, I feel.

**Comment by foresto** [comment]
I would be happy with that. My goal here is local linting without having to selectively replace my distro's dev tools or juggle config files. I think reverting the commit would achieve that, and probably make things easier for other potential contributors as well.

**Comment by deepbluev7** [comment]
Yeah, let's do that then. But I think we will migrate to clang-format14 once that is in alpine, which is simply incompatible with older versions and there seems to be no flag to fix that.

**Comment by foresto** [comment]
I'm on Debian, which is scheduled to adopt clang-format 14 in its next release. If Nheko jumps first and this incompatibility bites me again, I guess I can always submit another PR. :)

**Pull request merged**
