### PR TITLE
change 'redacted' for 'removed'

### PR DESCRIPTION
**Pull request by Kirillpt**
https://github.com/Nheko-Reborn/nheko/issues/329

### CODE REVIEW

**Review by LorenDB — CHANGES_REQUESTED** [review]
So far, so good; however, there are a lot of other locations in the code that refer to redacting. You may want to change those occurrences. 

See the attached screenshot for a list of files that I found that mention redactions.
Screenshot_20201126_090045

**Comment by Kirillpt** [comment]
> So far, so good; however, there are a lot of other locations in the code that refer to redacting. You may want to change those occurrences.
> 
> See the attached screenshot for a list of files that I found that mention redactions.
> Screenshot_20201126_090045
I thought about it. In matrix it's name of event, and maybe renaming in code can confuse other developers, or not?

**Comment by Kirillpt** [comment]
> > So far, so good; however, there are a lot of other locations in the code that refer to redacting. You may want to change those occurrences.
> > See the attached screenshot for a list of files that I found that mention redactions.
> 
> I thought about it. In matrix it's name of event, and maybe renaming in code can confuse other developers, or not?

And it's looks like that in mtx changes needed.

**Comment by deepbluev7** [comment]
Please only change the user visible strings, it is still a redaction on the protocol level. I think those changes look fine as they are :3

**Comment by deepbluev7** [comment]
Btw, for next time, if you fix an issue on github, adding "fix #issuenumber" or similar, will autoclose the issue, which makes it less effort for me :D

**Pull request merged**
