### PR TITLE
add regional indicator emojis (#1245)

### PR DESCRIPTION
**Pull request by Laevos**
Implements #1245, adding regional indicator emojis (https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B:Regional_Indicator=Yes:%5D) to the set of emojis. ~~I've put them in the "Flags" category as they're the building blocks of the flag emojis. However, if "Symbols" is a better place for them to live (Discord currently categorizes them as such), I can move them to that category.~~ EDIT: See update

Signed-off-by: Lilith McMullen <iggnsthe@live.com>

### CODE REVIEW

**Comment by Laevos** [comment]
Update: I looked through past examples and these seem to be better categorized as Symbols. I also see that there were some previous commits where regional indicators were dealt with: https://github.com/Nheko-Reborn/nheko/search?q=regional_indicator&type=commits. It appears that they may have been present previously but were then removed?

**Comment by deepbluev7** [comment]
We generate the emoji from the emoji_test.txt from the unicode group: https://unicode.org/Public/emoji/15.0/emoji-test.txt

That seems to not include regional indicators. It seems like at some point those were added as "extra_emoji.txt", but when regenerating the emoji cpp files I seem to have forgotten to include that file as well and just ran it on emoji.txt.

**Comment by deepbluev7** [comment]
It seems like the documentation was never updated for how to update the emoji to include the extra files: https://github.com/Nheko-Reborn/nheko/blob/master/scripts/update_emoji.md

**Comment by deepbluev7** [comment]
I fixed it slightly differently now, by just rerunning the regen command with the proper flags. Thank you for your contribution though and I hope it is okay that I solved it differently!

**Comment by Laevos** [comment]
Of course, I appreciate your time! It fell off my radar a bit so I'm glad to see traction on it. Thanks! On Jan 9, 2023 20:48, "DeepBlueV7.X" ***@***.***> wrote:
I fixed it slightly differently now, by just rerunning the regen command with the proper flags. Thank you for your contribution though and I hope it is okay that I solved it differently!

**Pull request closed without merging**
