### PR TITLE
drag left to reply

### PR DESCRIPTION
**Pull request by maltee1**
This works perfectly fine on desktop, just wait for me to test it on mobile.

### CODE REVIEW

**Comment by maltee1** [comment]
Please review and merge :)

**Comment by deepbluev7** [comment]
Nit, but aren't those directions the wrong way around? Wouldn't I drag to the roomlist to forward and drag to my messages to reply?

**Comment by maltee1** [comment]
That's another way to look at it. I wanted to drag in the same direction as the arrows (reply arrow in the hover menu points left). I also thought that other Messengers all do it that way, but that doesn't seem to be the case. Element drags left to reply, WhatsApp, Signal and Telegram drag right to reply (I think, I only have WhatsApp available to verify).

I suppose there isn't really a right and wrong for this. It's as simple as a couple of signs to change. It might make sense to have an option because it's easy to do and users may have strong opinions on this :D

**Comment by maltee1** [comment]
Well, I actually wanted swipe left to reply and keep swipe right to return to RoomList... But the latter doesn't work

**Pull request merged**
