### PR TITLE
support for hidden read receipts

### LINKED ISSUE #206: Read receipts toggle broken?
### Describe the bug

The setting "Read receipts" doesn't seem to do anything. This was probably broken in the migration to Qml (0.7.0). See also #205

### Expected behavior

It should either disable sending or disable receiving read receipts, I think, but not sure.
### System:

- Nheko version: 0.7.1
- Operating System: Gentoo
- Qt version: 5.14
- C++ compiler: gcc10
- Desktop Environment: KDE

### PR DESCRIPTION
**Pull request by symphorien**
depends on https://github.com/Nheko-Reborn/mtxclient/pull/72

fixes #206

### CODE REVIEW

**Comment by deepbluev7** [comment]
Looks good to me. One thing you need to fix still, there are commit hashes for mtxclient in the CMakelist.txt and io.github.NhekoReborn.nheko.yaml. You need to make those point at the recent mtxclient master so that the CI is happy.

Otherwise the reading of your own messages is a bit weird, but I see where you are coming from. Apart from this, this looks good, ty!

**Comment by symphorien** [comment]
The place where I leave hidden false is one where I could not find a way to use UserSettings::instance() actually.

**Comment by deepbluev7** [comment]
You should be able to use UserSettings::instance() everywhere, you just need to include the UserSettingsPage.h.

**Comment by symphorien** [comment]
do you prefer that I change that ?

**Comment by deepbluev7** [comment]
I think it will be less error prone to always send hidden receipts. Otherwise we will mess up at some point when refactoring. Does that sound alright?

**Comment by symphorien** [comment]
done

**Comment by deepbluev7** [comment]
Thank you! <3

**Pull request merged**
