### PR TITLE
Fix windows video bug

### LINKED ISSUE #500: Videos don't play on Windows
### Describe the bug
Can't run an uploaded video

### To Reproduce
1. Click send a file
2. Select a video to upload

### System:

- Nheko version: 0.8.1-1f8a3ae1
- Installation method: Local build
- Operating System: Windows
- Qt version: 5.15.2
- C++ compiler: msvc

image

### PR DESCRIPTION
**Pull request by Jedi18**
Fixes #500

### CODE REVIEW

**Comment by deepbluev7** [comment]
So this does break things on linux ._.

**Comment by deepbluev7** [comment]
```
[2021-03-14 21:07:49.141] [qml] [debug] media loaded: mxc://neko.dev/IRTttmvRoVlvOMRdEKbbdwnT at /home/nicolas/.cache/nheko/nheko/media_cache/neko.dev/IRTttmvRoVlvOMRdEKbbdwnT.mp4 (qrc:/qml/delegates/PlayableMediaMessage.qml:190, expression for onMediaCached)
[2021-03-14 21:07:49.141] [qml] [debug] media cached: mxc://neko.dev/IRTttmvRoVlvOMRdEKbbdwnT at /home/nicolas/.cache/nheko/nheko/media_cache/neko.dev/IRTttmvRoVlvOMRdEKbbdwnT.mp4 (qrc:/qml/delegates/PlayableMediaMessage.qml:192, expression for onMediaCached)
[2021-03-14 21:07:49.141] [qml] [debug] media loaded: mxc://neko.dev/IRTttmvRoVlvOMRdEKbbdwnT at /home/nicolas/.cache/nheko/nheko/media_cache/neko.dev/IRTttmvRoVlvOMRdEKbbdwnT.mp4 (qrc:/qml/delegates/PlayableMediaMessage.qml:190, expression for onMediaCached)
[2021-03-14 21:07:49.141] [qml] [debug] media cached: mxc://neko.dev/IRTttmvRoVlvOMRdEKbbdwnT at /home/nicolas/.cache/nheko/nheko/media_cache/neko.dev/IRTttmvRoVlvOMRdEKbbdwnT.mp4 (qrc:/qml/delegates/PlayableMediaMessage.qml:192, expression for onMediaCached)
[2021-03-14 21:07:49.141] [qml] [debug] Es wurde versucht, eine ungültige Qt-Ressource abzuspielen (qrc:/qml/delegates/PlayableMediaMessage.qml:175, onError)
[2021-03-14 21:07:49.141] [qml] [debug] Es wurde versucht, eine ungültige Qt-Ressource abzuspielen (qrc:/qml/delegates/PlayableMediaMessage.qml:175, onError)
```

**Comment by Jedi18** [comment]
Ok, made the changes.

**Comment by deepbluev7** [comment]
Jep, that works. Maybe could have used a comment, but eh.

**Pull request merged**
