### PR TITLE
support OpenBSD

### PR DESCRIPTION
**Pull request by klemensn**
- fix build/clear notifications on exit on OpenBSD
- Recognise OpenBSD on login page
- Honour Qt scaling factor on OpenBSD

### CODE REVIEW

**Comment by klemensn** [comment]
The official OpenBSD port has already been carrying the last two fixes as local patches.
The first I just wrote while updating to 0.9.2.

**Comment by deepbluev7** [comment]
Looks good on a first glance, why is it marked as a draft? :3

**Comment by klemensn** [comment]
> Looks good on a first glance, why is it marked as a draft? :3

Because 0.9.2 shows regressions and I still have no idea whether any of those hunks play a part in it.

**Comment by klemensn** [comment]
> > Looks good on a first glance, why is it marked as a draft? :3
> 
> Because 0.9.2 shows regressions and I still have no idea whether any of those hunks play a part in it.

d8669ccf3d4429e44caa87e2592b3bc3afa4e41c slows down my system so much that I have to kill nheko (once I manage that due to UI and input lag).
Reverting this on top of 0.11.3 yields a regular user experience, as 0.10.2 currently does.

**Comment by klemensn** [comment]
Now with 100% less typos, sorry for the noise.

**Comment by deepbluev7** [comment]
No worries, thanks a lot!

**Pull request merged**
