### PR TITLE
Replace the term Linux with GNU/Linux

### PR DESCRIPTION
**Pull request by LorenzoAncora**
GNU/Linux correctly refers to the entire OS.

### CODE REVIEW

**Comment by adasauce** [comment]
Ubuntu, Debian, and Gentoo Linux are proper names.

If you'd like to rename those projects, open a pull request upstream with them.

**Comment by deepbluev7** [comment]
I don't think this change makes sense either, since Nheko also runs on GNU-less systems, like Alpine or custom musl-based distributions.

**Comment by LorenzoAncora** [comment]
> Ubuntu, Debian, and Gentoo Linux are proper names.
> If you'd like to rename those projects, open a pull request upstream with them.

@adasauce `GNU/Linux` is not part of the distribution name, instead it is the correct name of the operating system: Linux refers only to the kernel, while GNU/Linux refers to the complete operating system. Debian itself wants users to use the term [GNU/Linux](https://www.debian.org/releases/jessie/amd64/ch01s02.html.en) instead of plain Linux, I quote:

> [...] Because the Linux kernel alone does not form a working operating system, **we prefer to use the term “GNU/Linux”** to refer to systems that many people casually refer to as “Linux”. --debian.org

This nomenclature is also part of the official name of the DVDs of the distribution, in fact by executing `cat/etc/os-release` this text is shown:

> PRETTY_NAME="**Debian GNU/Linux 10** (buster)"
> NAME="**Debian GNU/Linux**"

This is correct, because Debian and all derived distributions should be called GNU/Linux and not just Linux. [**Using the term GNU/Linux is very important**](https://www.gnu.org/gnu/gnu-linux-faq.html.en#why).

> I don't think this change makes sense either, since Nheko also runs on GNU-less systems, like Alpine or custom musl-based distributions.

@deepbluev7 this is a common misconception, as Alpine has GNU packages in its repositories: _bash_, _make_, _gcc_, and _coreutils_, so it is correct to call it Alpine GNU/Linux. A distribution is defined as GNU/Linux if it supports GNU packages, regardless of whether they are installed by default or not.
Even the simple copy command (<code>cp</code>) is a standard GNU tool, regardless if glibc is used or not.

As a member of the GNU Project, I ask you to use the term GNU/Linux: _using the term GNU/Linux is a sign of gratitude and responsibility towards those who develop the system you use every day_. 🙂

**Comment by adasauce** [comment]
> @adasauce `GNU/Linux` is not part of the distribution name, instead it is the correct name of the operating system: Linux refers only to the kernel, while GNU/Linux refers to the complete operating system. Debian itself wants users to use the term [GNU/Linux](https://www.debian.org/releases/jessie/amd64/ch01s02.html.en) instead of plain Linux, I quote:

precisely. `GNU/Linux` is not part of the name. you added those qualifiers to the proper names of the projects. the documentation did not say "Ubuntu Linux" or "Debian Linux". it referred to the projects by their names.

> 
> > I don't think this change makes sense either, since Nheko also runs on GNU-less systems, like Alpine or custom musl-based distributions.
> 
> @deepbluev7 this is a common misconception, as Alpine has GNU packages in its repositories: _bash_, _make_, _gcc_, and _coreutils_, so it is correct to call it Alpine GNU/Linux. A distribution is defined as GNU/Linux if it supports GNU packages, regardless of whether they are installed by default or not.
> Even the simple copy command (`cp`) is a standard GNU tool, regardless if glibc is used or not.
> 

while those packages are available for users to install in the repos, they don't make up alpine base. I can install coreutils in windows too, should we petition windows be renamed GNU/windows? 

strawmanning his argument works both ways -- and have a slippery slope while we're at it. we're not fighting about alpine specifically, and trying to poke holes in arguments with "well actually"s is no way to win favour if you'd like this change included.

the medium is the message :smile_cat:

**Comment by LorenzoAncora** [comment]
> <h2>strawmanning [...]</h2>

I am not a magician nor a mentalist. :-)

> while those packages are available for users to install in the repos, they don't make up alpine base. **I can install coreutils in windows too, should we petition windows be renamed GNU/windows**?

GNU/Linux is a term with historical roots, so you cannot say GNU/Windows because Windows is not a free operating system and the GNU tools are not native of such closed-source platform. In addition, the GNU Project does not endorse nor wants to be affiliated with closed-source software.

> precisely. GNU/Linux is not part of the name. you added those qualifiers to the proper names of the projects. the documentation did not say "Ubuntu Linux" or "Debian Linux". it referred to the projects by their names.

The term `Linux` refers **_only_** to the kernel.
`GNU/Linux` is part of the name of all distributions with a GNU userland, as I've demonstrated before with Debian GNU/Linux and its derivatives. If the repositories of the distribution offer the GNU tools (and so they are supported by the surrounding system environment and compatible with the kernel), then you should refer to the distributions as <code>GNU/Linux Distribution name</code>. So we say `GNU/Linux Debian` or `Debian GNU/Linux` equivalently, the same way we say ie. `Debian GNU/Hurd` when we refer to the version of Debian based on microkernel.

---

@deepbluev7 as you can see the text I've added is well motivated. If you think its excessive, we can search for a compromise and reduce the number of edited lines to the minimum: my interest as a member of the GNU Project is to guarantee both users and developers are informed, and as such it is not strictly necessary to repeat GNU/Linux for each distribution name but - at least - use the term GNU/Linux when appropriate. What do you think, can we reach an agreement?

**Comment by redsky17** [comment]
Given that nheko has no explicit dependencies on any GNU-specific projects, and given that it's quite possible to build an operating system with a linux kernel and no GNU-related parts (that nheko will still work on), I don't think it makes sense to specify GNU/Linux everywhere instead of just 'Linux.'  Back to the alpine example, it ships out of the gate with Busybox, rather than coreutils.  Yet, nheko still has a package available on alpine.  What I'm getting at is, changing the wording in our readme to GNU/Linux vs just 'Linux' implies that it runs on fewer operating systems than it does.  Further, Linux is the more widely used term in the media and across the internet at large.

I understand your opinion and where you are coming from, but please do not try to impose this on our project or our user base.  We are not part of the FSF or GNU Project.

**Comment by deepbluev7** [comment]
Also if you look at the web pages of most Linux distributions, they don't even say GNU/Linux on that page, i.e.: https://www.debian.org/ or https://ubuntu.com/. I don't see a reason, why we should use something different than the official name the distribution uses.

I also don't want to list every contributor to the Linux ecosystem in our README. that much text makes it hard to read. So I think we'll just stay with Linux, since everybody knows, what is meant by that.

**Comment by MasterOfTheTiger** [comment]
Note that Debian does often refer to itself as GNU/Linux. (While I agree that calling it just "Debian" makes the most sense here).

**Comment by LorenzoAncora** [comment]
> [...] I understand your opinion and where you are coming from, but please do not try to **impose this on our project or our user base**. We are not part of the FSF or GNU Project.

@redsky17 there is a reason if it is called Pull _Request_: it can be rejected. If I wanted to impose something on you, I wouldn't have asked before. :-)

> [...] Given that nheko has no explicit dependencies on any GNU-specific projects, and given that it's quite possible to build an operating system with a linux kernel and no GNU-related parts (that nheko will still work on), I don't think it makes sense to **specify GNU/Linux everywhere** instead of just 'Linux.' [...]

The Pull Request adds the correct abbreviation where possible and correct, not only where strictly necessary. GitHub allows you to make arbitrary changes, eliminating the parts that you feel are excessive for your project.

> [...] **BSD systems typically have GNU software available in ports, yet they are not 'GNU/BSD' operating systems**. [...]

This is a common misconception. :-)
[GNU/kFreeBSD](https://en.wikipedia.org/wiki/Debian#Debian_GNU/kFreeBSD) existed.
In general, for historical and licensing reasons, the oldest BSD systems are not called GNU/BSD but only BSD. This is a special and universally accepted _exception_ to the use of the term GNU in names.

> What I'm getting at is, **changing the wording in our readme to GNU/Linux vs just 'Linux' implies that it runs on fewer operating systems** than it does. Further, **Linux is the more widely used term in the media and across the internet at large.**

There are compatibility tools for porting any software: if everyone did the same reasoning, nobody would use the correct term.

---

> Also if you look at the web pages of most Linux distributions, they don't even say GNU/Linux on that page, i.e.: https://www.debian.org/ or https://ubuntu.com/. **I don't see a reason, why we should use something different than the official name the distribution uses.**

@deepbluev7 this is not correct, as GNU/Linux is part of the official name of Debian and all its derivatives.
In Debian, official CDs/DVDs [covers](http://debian.semistable.com/cdcover.pl) use the wording GNU/Linux; the same is true for many of the [web graphics](https://www.debian.org/logos/button-1.gif).
The Ubuntu installation guide has even a [dedicated page](https://help.ubuntu.com/lts/installation-guide/s390x/ch01s03.html) which explains what is GNU/Linux.
These distributions omit the whole "GNU/Linux" when there might be space issues, but in official documentation there is always a reference on the fact that the correct name includes GNU/Linux and not just Linux.

> **I also don't want to list every contributor to the Linux ecosystem in our README**. that much text makes it **hard to read**.

GNU is not a contributor, instead it is a fundamental part: without GNU, Linux would have remained a kernel, useless on its own. Also, I think adding 3 letters cannot make anything harder to read. At least, I am visually impaired and I have no difficulty reading the upgraded README.
If you are really concerned with readability, just append this to the footer:

  ```* to save space, "Linux" is used in place of "GNU/Linux".```

I think result is the same.

> So I think we'll just stay with Linux, since everybody knows, what is meant by that.

The large GNU community considers the incorrect use of the term Linux as an "anti-feature", a definition similar to the concept of bug but with a negative moral connotation. This moral judgment often extends from the software to its developers.
The GNU community independently evaluates all free software and negatively [marks](https://directory.fsf.org/wiki/Free_Software_Directory:Antifeatures#.22Linux_System.22) software that does not respect the correct use of the term GNU/Linux.
It should be a good idea to gain and preserve a good reputation in that community, which is why I went through here well in advance, but everyone has their own moral yardstick in good or bad.

Having said that, I can't do anything else for you. Have a good time. :-)

**Pull request closed without merging**
