### PR TITLE
Place metadata next to content if there is space

### PR DESCRIPTION
**Pull request by maltee1**
to be fixed: metadata overlaps NoticeMessage content

### CODE REVIEW

**Comment by deepbluev7** [comment]
Preferably you would make one PR for each of those things <3

**Comment by maltee1** [comment]
You're the senate :D

**Comment by maltee1** [comment]
I consider this ready for merging.

**Comment by deepbluev7** [comment]
In some cases there seems to be a bit too much spacing, but otherwise it looks great, thanks a lot!

**Pull request merged**
