### PR TITLE
Add member list and settings buttons to spaces

### PR DESCRIPTION
**Pull request by LorenDB**

### CODE REVIEW

**Comment by deepbluev7** [comment]
Mhm, any screenshots? :D

**Comment by LorenDB** [comment]
Well, I can, but I'll have to rebuild since I already switched to another branch :/

**Comment by LorenDB** [comment]
image
The buttons open the member and settings dialogs just like it would be a regular room.

**Comment by deepbluev7** [comment]
Why not make the member count a button instead? And maybe add a little cog next to the space name or avatar for the settings? I was hoping to use the space below the topic to show the latest few discussions from the child rooms or something other interesting.

**Comment by LorenDB** [comment]
Isn't the member count already a button?

**Comment by deepbluev7** [comment]
Then why add another one?

**Comment by LorenDB** [comment]
OH! I get what you mean now.

**Comment by LorenDB** [comment]
Fixed the button stuff.

**Comment by LorenDB** [comment]
> Thanks! If you want, I'll add the member button to the room settings dialog in #1056.

Done

**Pull request merged**
