### PR TITLE
Ignore a few files that should never be committed

### PR DESCRIPTION
**Pull request by LorenDB**
The MOC files and the QRC files make for huge outputs from `git status`.

### CODE REVIEW

**Comment by deepbluev7** [comment]
This only happens, if you don't build in a folder starting with `build`. Just do that instead. You should never do an in source build!

**Comment by LorenDB** [comment]
I *do* build in a build folder!

**Comment by deepbluev7** [comment]
Then those should not show up in git status at all.

**Comment by LorenDB** [comment]
Never mind, I was confused about how an in-source build works.

**Pull request closed without merging**
